# Generated by Django 2.1.1 on 2018-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertys', '0003_auto_20181005_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floorplan',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='mapping',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
