# Generated by Django 2.1.1 on 2018-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertys', '0006_auto_20181015_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
